on: push

jobs:
  build-apax-lib:
    uses: simatic-ax/actions/.github/workflows/apax-build.yml@kruegerf-feat-reusable
    secrets:
      APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
    with:
      ACTIONS_REF: kruegerf-feat-reusable

  test-apax-lib:
    needs: build-apax-lib
    uses: simatic-ax/actions/.github/workflows/apax-build-test.yml@kruegerf-feat-reusable
    secrets:
      APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
