on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'  

jobs:
  release-apax-lib:
    uses: simatic-ax/actions/.github/workflows/apax-publish.yml@kruegerf-feat-reusable
    secrets:
      APAX_TOKEN: ${{ secrets.APAX_TOKEN }}
    with:
      VERSION: ${{ github.ref_name }}
