name: Renovate
on:
  workflow_dispatch:
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@stable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Login to simatic-ax registry"
        if: ${{ inputs.LOGIN_SIMATIC_AX }}
        run: |
          apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.TOKEN_GITHUB }}