name: Renovate
on:
  workflow_dispatch:
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@stable
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Login to simatic-ax registry"
        if: ${{ inputs.LOGIN_SIMATIC_AX }}
        run: |
          apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: install_apax
        shell: bash
        env:
          APAX_TOKEN: ${{ inputs.APAX_TOKEN }}
        run: |
          sudo curl -H "Authorization: bearer $APAX_TOKEN" "https://api.simatic-ax.siemens.io/apax/login?format=npmrc" -o .npmrc --verbose
          cat .npmrc
          export APAX_NPMRC=.npmrc
          echo $APAX_NPMRC
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.82.0
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.TOKEN_GITHUB }}